### ISSUE TITLE
KVKK Onay Butonu

### ISSUE THREAD

**Issue by tnygns** [VB10/sesimiduy#27]
"Yardim Istiyorum" ve "YArdima Gidiyorum" formlarinda ,

1- " Okudum ve aydinlandim. " checkBox koyulup,  hyperlink olarak asagidaki wordun eklenmesi .
2- checkBox isaterlendikten sonra onay butonunu aktiflestirilmesi.

[KVKKmetni.docx](https://github.com/VB10/sesimiduy/files/10711381/KVKKmetni.docx)

**Comment by VB10** [comment]
@aliaydogdu000
