### ISSUE TITLE
📌 Data Team: Feedback

### ISSUE THREAD

**Issue by TarikKaanKoc** [VB10/sesimiduy#45]
### Web App
----
* Web açıldığında default olarak ingilizce dili geldi.   https://github.com/VB10/sesimiduy/issues/37
* Ana sayfada, button'lar ile ilgili update gerçekleştirilecek. (Bununla ilgili suanda Tuğba hanım figma üzerinden güncelliyor tasarımı.)

### Geliştirilecek Noktalar: UI & Data Ekibi 
* il ilce secerken dropdown menude alalim ([depremyardim.com](http://depremyardim.com/) gibi) Tuğba hanım yine gerekli güncellemeyi gerçekleştirecek. Ek olarak diğer feature'lar üzerinde drop down menu item’larin ingilizceleri/Türkçeleri hazırlanacak.
* Neye ihtiyacimiz var kisminda item eksikliği giderilmeli ve UI Güncellenmeli.
* Neye ihtiyacimiz var kismindaki item eksikliği giderilmeli ve UI Güncellenmeli.

### HARİTA
Kullanıcı tüm araçları görüntüleyebilecek mi? Görüntüleyememesi daha doğru olmaz mı? VB Maddeler mevcut.  Bunun üzerine 19:30'da data  ve product manager ile toplantı gerçekleştireceğiz .Geri bildirimi sağlayacağız. 

Teşekkürler. 
**Tarık Kaan Koç**

**Comment by VB10** [comment]
@TarikKaanKoc butonlar guncellendi, dil sorunu cozuldu

**Comment by TarikKaanKoc** [comment]
@VB10 Teşekkür ederiz. Arpaç dil desteği için bir json dosyası ekledim incelersiniz hocam https://github.com/VB10/sesimiduy/pull/59

**Comment by VB10** [comment]
aldim ekliyorum destege
