### ISSUE TITLE
Öykü - Geri Bildirim

### ISSUE THREAD

**Issue by oykuozgen** [VB10/sesimiduy#56]
Ellerinize sağlık öncelikle; ben bu feedbackte yine de yazım yanlışlarına vs de yer verdim. Belki yazdıklarım tam olarak sizin istediğiniz feedbacki karşılamayabilir ancak bazıları sizlik değilse lütfen oraları es geçin ve beni mazur görün. Kendim adına dikkat etmem için notlar almışım gibi kabul edin oralarını. Daha çok tasarım ve kullanım kolaylığıyla alakalı değineceğim bazı noktalara.

Anasayfa

- [x] Sağ üst köşe dil butonu çok dipte ve ufak kalmış okunmayı zorlaştığı için onu biraz sola çekip büyütelim.
- [x] Üstteki logoyu yukarı doğru biraz daha alıp büyütelim.
- [x] “Afet alanına yardım ulaştıracak olan araçları ve yardıma ihtiyacı olanları buluşturan uygulama” yazalım.
- [x] 1. Butonda “YARDIM İSTİYORUM“ şeklinde Türkçe karakter düzeltmesi yapalım.
- [x]  Altta sosyal medya butonlarına linklerini ekleyelim ve 
- [x] bu bir sosyal sorumluluk projesidir yazısını butonların Yardıma Gidiyorum vs butonlarının altına doğru alalım ve o boş alanı yok edelim.

**Yardım İstiyorum Sayfası**

- [x] “Yardıma ihtiyacı olan kişinin;” (noktalı virgül eksiği) şeklinde yazalım ya da Yardıma İhtiyacı Olan Kişinin şeklinde değiştirelim.

- [ ]  Formu yanlış doldurunca yanlış doldurdunuz uyarısı verebilelim, mesela soyadını eklemediğinde eksik bir form oluyor aslında. Onu ekleyelim.

- [ ] Adresi doğru bir sırayla yazmasını sağlayabilir miyiz ya da kategori olarak kendi seçebilir mi şu mahalle vs diye 

- [ ] Neye ihtiyacınız var kısmına bizim belirlediklerimizin dışında kategoriler yazmasını sağlayabiliyor muyuz? 
Bu bize çeşitli sorunlar doğurur mu? Üzerine tartışalım.

- [x] Yardım İstiyorum alanına da sosyal medya butonlarımızı, logomuzu, dil seçeceğini ekleyelim. 

- [x] Yardım İste formunu doldurduktan sonra onu haritaya yönlendirelim ki site ve uygulama içerisinde kalarak yardım yerlerine uğrayıp bakmasını sağlayalım. Özellikle yardım istediği konularda pinli şekilde olan haritayı ona gösterelim. Onla alakası olmayan alanı filtre kısmından halledebilsin. Yapılabiliyor ise tabi ki.

- [x] KVKK metnini ekleyelim.

Alttaki boş alanı temizleyelim.

**Bireysel Yardım**

- [x] Metinleri düzenleyelim.

- [x] #70

- [ ] Telefon kısmında ev numarasını yazmasını engelleyelim.

- [ ] Adresleri alfabetik sıraya göre düzenleyelim.

- [x] Yardımın gittiği şehri deprem bölgeleri olan 10 şehirle sınırlayalım.

- [ ] Araç plaka no yazınca buton büyüyor ve kayıyor. Onu bilerek mi yaptık?

- [x] Yardımı götür yazısı koyu renkle yazılırsa iyi olabilir grinin üzerinde beyaz göz kontrast değerini karşılamadığı için okunmuyor.

- [ ] Yardıma götür butonuna tıkladıktan sonra harita sayfasını açalım ve kişinin konumunu baz alarak gideceği yere filtrelenmiş bir harita ekleyelim. Ayrıca yardıma ihtiyacı olan kişileri de aynı haritada kişinin gönderdiği ürünlerle eşleyen kişileri sadece gösterelim. Eğer tırsa bu araç tırların çekildiği komuta merkezini daha büyük gösterebiliriz.

Geçici barınma alanlarında kişinin daha önce verilerine göre bir harita sunmasını sağlayalım.

**Haritada info alanının konum iconunu ortalayalım ve metin alanını biraz sola kaydırıp ortalayalım ve oraya burada bu yardım çözümü yok ya da burada bu yardıma ihtiyacı olan yok gibi bir doğrulama butonu koyalım. Onları panelde biriktirip panelden bu sorunları tespit edip görebilelim.**

Eğer yapabiliyorsak bu şekilde yorumlara altta kutucuklar şeklinde webde birden çok göstermek güzel olabilir.

Haritada filtreleme alanımızı akordiyon menü yerine açık hale getirip görmesini kolaylaştıralım ve yazı boyutunu büyültelim. 

Kategoriler kısmında ise;

- [x] Geçici yazılmış vs vs Geçici Barınma Alanları yazısını vs düzeltelim.

- [ ] Logomuzu bu alana da yukarıdaki bölgeyi büyüterek ortalayıp koyalım.

- [x] #71

Ellerinize sağlık, belki yazdıklarımın bazıları tam sizin istediğiniz şeyler değildir. Lütfen bu konuda kusuruma bakmayın. Tüm emekleriniz için teşekkür ederim.

**Comment by VB10** [comment]
@oykuozgen ilk yapilmasi gerekenleri ekledik bu bazi yazdiklariniz icin biraz daha detayli girerseniz misal kvkk metninin ne olacagi gibi biz oraya link ekledik veya misal burada bir istek var onu figmaya koydurtursaniz figmadaki gibi yapalim derseniz direk sorunlar daha iyi cozulmus olur
