### ISSUE TITLE
POI guncel bilgiler

### ISSUE THREAD

**Issue by tnygns** [VB10/sesimiduy#60]
HAritalardaki statik pinlenecek POI bilgileri asagidaki exceldeki gibidir.
[POI_afetbilgi0213_yardimNoktalari.xlsx](https://github.com/VB10/sesimiduy/files/10722090/POI_afetbilgi0213_yardimNoktalari.xlsx)

json file ve ve json URL eklenmisitr.

https://cdn.afetbilgi.com/maps/latest.json
[POI_afetbilgi0213_yardimNoktalari.xlsx](https://github.com/VB10/sesimiduy/files/10722915/POI_afetbilgi0213_yardimNoktalari.xlsx)

- [ ] POI aciklamarinda POI ye rota olusturulabilinmeli
- [x] POI aciklamalarinda POI tipi belirtilmeli
- [x] POI tiplerine gore pinler farkli olmali

**Comment by tnygns** [comment]
json file ve ve json URL eklenmisitr.

https://cdn.afetbilgi.com/maps/latest.json
[POI_afetbilgi0213_yardimNoktalari.xlsx](https://github.com/VB10/sesimiduy/files/10722915/POI_afetbilgi0213_yardimNoktalari.xlsx)

**Comment by VB10** [comment]
@tnygns poi'ye rota olusturma tiklayip git maks bir duz seklinde olur diger noktada google api'den supprot lazim
- poi tip renkleri custom olarak set etmeyi plannliyorum secilenin yaninda kutu olabilir 5-6 renk atilabilir
-

**Comment by VB10** [comment]
@berkancnr bu bizdeki poi datalarini bunla guncellemiz lazim

**Comment by tnygns** [comment]
> @tnygns poi'ye rota olusturma tiklayip git maks bir duz seklinde olur diger noktada google api'den supprot lazim
> 
> * poi tip renkleri custom olarak set etmeyi plannliyorum secilenin yaninda kutu olabilir 5-6 renk atilabilir

o zaman simdilik bu sekilde yapalim sonra google credici gelince "get direction" olayina bakariz
