### ISSUE TITLE
Yardim Istiyorum sayfasinda Tasinan malzemeler dropdown menusu

### ISSUE THREAD

**Issue by tnygns** [VB10/sesimiduy#64]
Yardima Istiyorum sayfasinda Tasinan malzemeler dropdown menusude  listede olmayan malzemelerde girilebilmeli.

**Comment by AcarFurkan** [comment]
abi selam, öncellikle ellerinize kolarınıza sağlık proje çok güzel olmuş. 
kategorilerin sayılarını arttırıp ihtiyaç tanımını açıklamak için bir field eklemek sizce nasıl olur? 
Bu alan doldurulmak zorunda değil ancak yardım edicek kişinin problemi veya ihtiyacı daha iyi anlamasına yardımcı olabilir.
Bizde benzer bir proje geliştiriyoruz aşağıya kast ettiğim field ın görüntüsünü bırakıyorum. birde ağırlıklı talep edilen kategorilerimizide bırakıyorum belki işinize yarayabilir. 
Ayrıca elimden ne gelirse yapmayada hazırım issue lara bakıyorum :) 
<img width="498" alt="image" src="https://user-images.githubusercontent.com/65075121/218721498-ac55faac-1226-40f2-8599-63191bd20b2f.png">


(Bebek Kıyafet)
(Gıda)
(Bebek Maması)
(İlk Yardım)
(Barınma)
(Kıyafet)
(Hijyen)
(Isıtma)
(İletişim)
(Arama Kurtarma Gereçleri)
(Elektrik/Elektronik)
(Ayakkabı)
(İlaç)
(Sosyal)
(Diğer)
(Jeneratör)
(Işıklandırma)

**Comment by VB10** [comment]
@AcarFurkan eline emeğine sağlık onları ya böyle kategori yapıcaz yada şuanki yapıda otomatik eklenecek onu takip edioyruz

**Comment by tnygns** [comment]
Listede olmayan malzemelerin de girilmesini ekleyebilir miyiz?
