### ISSUE TITLE
IOS browserda anasayfa fit degil

### ISSUE THREAD

**Issue by tnygns** [VB10/sesimiduy#67]
IOS browserda anasayfa fit degil
![IOS Browser Anasayfa](https://user-images.githubusercontent.com/83843961/218476713-f6ab3b80-9916-45c7-8346-574f9c8d45f4.jpeg)

Iphone 13 pro max da sorun yok,
Iphone 14,12, 11, 8  de sorun tespit edildi

**Comment by Krdnzbyza** [comment]
bu issue son eklenen pr da düzeltilmişti @VB10 issue kapatılabilir
