### ISSUE TITLE
Map

### ISSUE THREAD

**Issue by TarikKaanKoc** [VB10/sesimiduy#68]
- [x] Harita açıldığında direkt kullanıcının güncel konumu görüntülenmeli

**Comment by VB10** [comment]
@TarikKaanKoc burada adam izin vermemis olabilir bu durumda ortak bir point olabilir maras misal

**Comment by TarikKaanKoc** [comment]
> @TarikKaanKoc burada adam izin vermemis olabilir bu durumda ortak bir point olabilir maras misal

Eğer izin vermemiş ise bunu sağlayabiliriz. Örnek olması bakımından: maps.afetbilgi.com

**Comment by alperenekin** [comment]
İzin verildiği durumla ilgileniyorum o halde

**Comment by VB10** [comment]
@alperenekin ben ekledim bunu
