### ISSUE TITLE
Yeni Eklenebilecek İstekler 13.02.2022

### ISSUE THREAD

**Issue by Krdnzbyza** [VB10/sesimiduy#71]

**Comment by Krdnzbyza** [comment]
**Teslim ettim alanında Kime teslim edildiğine dair ek alan eklenmesi talep edilmektedir**
<img width="512" alt="Screenshot 2023-02-13 at 23 13 43" src="https://user-images.githubusercontent.com/57248151/218564932-f1a8e9ea-e898-4cdc-a8eb-eac5a639f4ff.png">

**Comment by Krdnzbyza** [comment]
teslim ettim alanında kime teslim edildiğine dair ek alan eklenmesi talep edilmektedir

**Comment by Krdnzbyza** [comment]
**Harita kısmında baslık kısmında ortaya logo eklenmesi**
<img width="1697" alt="Screenshot 2023-02-13 at 23 17 23" src="https://user-images.githubusercontent.com/57248151/218565611-3eb7ec42-6736-431e-8007-2b03b4e57f7a.png">

**Comment by Krdnzbyza** [comment]
Telefon Numarası alanı formatlanması gerekmektedir. İstenen : 

- [Ülke kodu istenildiği gibi girilebilecek +90 seklinde ](https://github.com/VB10/sesimiduy/issues/69)
- Ev telefonu girilmesi istenmiyor?

<img width="438" alt="Screenshot 2023-02-13 at 23 21 44" src="https://user-images.githubusercontent.com/57248151/218566413-17005f81-6146-4ccc-8d98-4519834eb6a7.png">

**Comment by Krdnzbyza** [comment]
[ **Harita açıldığında direkt kullanıcının güncel konumu görüntülenmeli** ](https://github.com/VB10/sesimiduy/issues/68)

**Comment by VB10** [comment]
@TarikKaanKoc 
<img width="2141" alt="image" src="https://user-images.githubusercontent.com/17102578/218620378-b75ae34c-a5a6-4f85-9f5d-64a216d652af.png">
