### ISSUE TITLE
firebase edit yetkisi verilecek email listesi

### ISSUE THREAD

**Issue by tnygns** [VB10/sesimiduy#74]
firebase edit yetkisi verilecek email listesi

tnygns@gmail.com
enes2277@gmail.com
ezgisubasi1998@gmail.com
tarikkaan1koc@gmail.com
bugraerdagg@gmail.com

**Comment by tnygns** [comment]
2 adminimizide ekleyebilir misiniz ?
Erdal.genc09@gmail.com
isilkobak@gmail.com

**Comment by VB10** [comment]
eklendi hepsi @tnygns

**Comment by tnygns** [comment]
firebase erisimini nasil saglayacagiz? 
admin panel bilgilerini alabilir miyim ?
