### ISSUE TITLE
Mobilden web sitesini açınca tüm butonların gözükmeme problemi

### ISSUE THREAD

**Issue by isilkobak** [VB10/sesimiduy#83]
Mobilden web sitesini açınca yalnızca ilk iki buton gözüküyo alttakilerin olduğu anlaşılmayabili hepsi ekrana sığmalı
![2B83FD1F-71E9-4330-818A-83143DAD24A1](https://user-images.githubusercontent.com/34427049/218696561-c2ea1d9c-97e5-4c90-9052-ec642ca7c5a6.png)

**Comment by isilkobak** [comment]
Iphone 14 ile açtım

**Comment by VB10** [comment]
@MehmetKaranlik burada 4 butonu gird yapıp erkanda küçültsek dahi göseterelim veya sosyal medya alanları altta kalsın butonların sizeleri küçlmesin
