### ISSUE TITLE
Haritadaki POI info box konum istenmesi

### ISSUE THREAD

**Issue by tnygns** [VB10/sesimiduy#89]
Haritadaki POI info boxda yardim isteyenin konumundan POI ye duz cizgi ile rota belirlenmesinin yapilmasi

**Comment by VB10** [comment]
sen istersin yapmazmiyim 
![image](https://user-images.githubusercontent.com/17102578/218893360-59fa2ca3-5ebf-4283-92f8-54cf1e115894.png)
