### ISSUE TITLE
🛠 Items-json

### ISSUE THREAD

**Issue by TarikKaanKoc** [VB10/sesimiduy#90]
- [x] Aşağıdaki item'lar yardıma gidiyorum "Neye İhtiyacınız Var"? ve yardım istiyorum tarafında "Taşınan Malzemeler" 'de yer alacak olan item'lardır. 

#### Eklenecek item'lar: 

```python
{
"items": [
"Su",
"Gıda",
"Çadır",
"Isınma (Ufo vb)",
"Ayakkabı",
"Jeneratör",
"Işıklandırma",
"Bebek Kıyafeti",
"Çocuk Kıyafeti",
"Kadın Kıyafeti",
"Erkek Kıyafeti",
"Çocuk Mont",
"Kadın Mont",
"Erkek Mont",
"Hijyen Malzemesi",
"Battaniye / Yorgan",
"Yastık",
"Kedi Maması",
"Köpek Maması"
]
}
```

**Comment by MehmetKaranlik** [comment]
@VB10  @TarikKaanKoc veriler şu an firebase'e eklendi güncel olarak appten çekilebiliyor.
