### ISSUE TITLE
"Yardima Gidiyorum" ve  "yardim iste" butonu onaylandi safyasina yonlendirmiyor

### ISSUE THREAD

**Issue by tnygns** [VB10/sesimiduy#94]
"Yardim istiyorum" sayfasinda "yardim iste" butonu onaylandi safyasina yonlendirmiyor
"Yardima gidiyorum" sayfasinda "yardim gotur" butonu onaylandi safyasina yonlendirmiyor

**Comment by VB10** [comment]
buradaki tum eklemeler yapidli app gunclelendi adnroid ve ios olmak uzere sadece suanki google paketindeki bir sorundan oturu website mobil phone browserinde calisiyior oda anlik olarak hata olma ihtmiali var eger andorid appten bakarsaniz hepsi bitmis olarak gozukecektir. ilgili issuede burada daha bu gece acildi bekliyorum bende sonucnu

https://github.com/firebase/flutterfire/issues/10474

**Comment by VB10** [comment]
@tnygns son olarak siteyi guncleledim o sorunu da cozdum
